version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - avatar-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - avatar-network

networks:
  avatar-network:
    driver: bridge

volumes:
  redis-data: